return {
	
	Enable_TopbarPlus = false,
	Path_To_TopbarPlus = nil,
	
	Enable_NexusVR_Compat = false,
	
	Enable_VRBottomBar = false,
	Path_To_VRBottomBar = nil,
	VRBottomBar_Position = 1,
	
	Adonis_Compat = false,
	Technified_Compat = false,
	
	Phrases = {
		["Formalities"] = {
			Hello = {Text = "Hello!"},

			Bye = {Text = "Bye!"},
			ByePlayer = {Text = "Bye, {player}!"},
		},

		["Requests"] = {
			CanYouFollowMe = {Text = "Can you follow me {player}?"},
		},

		["Answers"] = {
			Yes = {Text = "Yes"},
			No = {Text = "No"},
			What = {Text = "What?"},
		}
	},
	
	UI = {
		Stroke_Color = Color3.fromRGB(255, 0, 255),
		Stroke_Thickness = 2,
		Stroke_Transparency = 0,
		
		Background_Color = Color3.fromRGB(140, 0, 140),
		
		Use_Formatting = true,
		PlayerNameColor = "#FFFFFF",
		PlayerMessageColor = "#FFFFFF",
		
		Welcome_Message = true,
	},
	
	Chat_Cooldown = 2,
	
	DebugMode = false,
	
	
	
	--// System Specific
	Version = "1.1.1",
}