blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/8fWuYzMnrR
    about: Please submit your questions here. Join our community server to talk to the Community and to easily contact Maintainers