name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Lint (Selene)
        run: selene Loader MainModule

      - name: Build place file (Rojo)
        run: rojo build default.project.json --output Quickchat.rbxl

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: quickchat-build
          path: Quickchat.rbxl